package model.compiler;

//#############################################
//## file: Parser.java
//## Generated by Byacc/j
//#############################################
/**
 * BYACC/J Semantic Value for parser: Parser
 * This class provides some of the functionality
 * of the yacc/C 'union' directive
 */

public class ParserVal {
    /**
     * Integer value of this 'union'
     */
    public int ival;
    
    /**
     * Double value of this 'union'
     */
    public double dval;
    
    /**
     * String value of this 'union'
    */
    public String sval;
    
    /**
     * String value of this 'union'
    */
    public Object obj;
    
    //#############################################
    //##        C O N S T R U C T O R S
    //#############################################
    /**
    * Initialize me without a value
    */
    public ParserVal(){}
    
    /**
    * Initialize me as an int
    */
    public ParserVal(int val){
        this.ival = val;
    }

    /**
     * Initialize me as a double
     */
    public ParserVal(double val){
      this.dval = val;
    }

    /**
     * Initialize me as a string
     */
    public ParserVal(String val){
      this.sval = val;
    }

    /**
     * Initialize me as an Object
     */
    public ParserVal(Object val){
        this.obj = val;
    }
}// end class

//#############################################
//## E N D    O F    F I L E
//#############################################